// Code generated by protoc-gen-go.
// source: regfile.proto
// DO NOT EDIT!

/*
Package main is a generated protocol buffer package.

It is generated from these files:
	regfile.proto

It has these top-level messages:
	FownEntry
	RegFileEntry
*/
package main

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type FownEntry struct {
	Uid              *uint32 `protobuf:"varint,1,req,name=uid" json:"uid,omitempty"`
	Euid             *uint32 `protobuf:"varint,2,req,name=euid" json:"euid,omitempty"`
	Signum           *uint32 `protobuf:"varint,3,req,name=signum" json:"signum,omitempty"`
	PidType          *uint32 `protobuf:"varint,4,req,name=pid_type" json:"pid_type,omitempty"`
	Pid              *uint32 `protobuf:"varint,5,req,name=pid" json:"pid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *FownEntry) Reset()                    { *m = FownEntry{} }
func (m *FownEntry) String() string            { return proto.CompactTextString(m) }
func (*FownEntry) ProtoMessage()               {}
func (*FownEntry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *FownEntry) GetUid() uint32 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *FownEntry) GetEuid() uint32 {
	if m != nil && m.Euid != nil {
		return *m.Euid
	}
	return 0
}

func (m *FownEntry) GetSignum() uint32 {
	if m != nil && m.Signum != nil {
		return *m.Signum
	}
	return 0
}

func (m *FownEntry) GetPidType() uint32 {
	if m != nil && m.PidType != nil {
		return *m.PidType
	}
	return 0
}

func (m *FownEntry) GetPid() uint32 {
	if m != nil && m.Pid != nil {
		return *m.Pid
	}
	return 0
}

type RegFileEntry struct {
	Id               *uint32    `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Flags            *uint32    `protobuf:"varint,2,req,name=flags" json:"flags,omitempty"`
	Pos              *uint64    `protobuf:"varint,3,req,name=pos" json:"pos,omitempty"`
	Fown             *FownEntry `protobuf:"bytes,5,req,name=fown" json:"fown,omitempty"`
	Name             *string    `protobuf:"bytes,6,req,name=name" json:"name,omitempty"`
	MntId            *int32     `protobuf:"zigzag32,7,opt,name=mnt_id,def=-1" json:"mnt_id,omitempty"`
	Size             *uint64    `protobuf:"varint,8,opt,name=size" json:"size,omitempty"`
	Ext              *bool      `protobuf:"varint,9,opt,name=ext" json:"ext,omitempty"`
	Mode             *uint32    `protobuf:"varint,10,opt,name=mode" json:"mode,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *RegFileEntry) Reset()                    { *m = RegFileEntry{} }
func (m *RegFileEntry) String() string            { return proto.CompactTextString(m) }
func (*RegFileEntry) ProtoMessage()               {}
func (*RegFileEntry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

const Default_RegFileEntry_MntId int32 = -1

func (m *RegFileEntry) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *RegFileEntry) GetFlags() uint32 {
	if m != nil && m.Flags != nil {
		return *m.Flags
	}
	return 0
}

func (m *RegFileEntry) GetPos() uint64 {
	if m != nil && m.Pos != nil {
		return *m.Pos
	}
	return 0
}

func (m *RegFileEntry) GetFown() *FownEntry {
	if m != nil {
		return m.Fown
	}
	return nil
}

func (m *RegFileEntry) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *RegFileEntry) GetMntId() int32 {
	if m != nil && m.MntId != nil {
		return *m.MntId
	}
	return Default_RegFileEntry_MntId
}

func (m *RegFileEntry) GetSize() uint64 {
	if m != nil && m.Size != nil {
		return *m.Size
	}
	return 0
}

func (m *RegFileEntry) GetExt() bool {
	if m != nil && m.Ext != nil {
		return *m.Ext
	}
	return false
}

func (m *RegFileEntry) GetMode() uint32 {
	if m != nil && m.Mode != nil {
		return *m.Mode
	}
	return 0
}

func init() {
	proto.RegisterType((*FownEntry)(nil), "main.fown_entry")
	proto.RegisterType((*RegFileEntry)(nil), "main.reg_file_entry")
}

func init() { proto.RegisterFile("regfile.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 221 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x4c, 0x8e, 0xb1, 0x6a, 0xc3, 0x30,
	0x10, 0x40, 0x91, 0xac, 0xb8, 0xce, 0x39, 0x0e, 0xa9, 0xa6, 0x9b, 0x8a, 0xc8, 0xa4, 0xa5, 0x86,
	0x76, 0xec, 0x87, 0x74, 0x35, 0x06, 0x9d, 0x8d, 0x20, 0x92, 0x8c, 0xad, 0xd0, 0xa6, 0xbf, 0xd3,
	0x1f, 0x2d, 0x27, 0x42, 0xc9, 0xf8, 0xa4, 0xbb, 0x77, 0x0f, 0xba, 0x95, 0xe6, 0xc9, 0x5f, 0xa8,
	0x5f, 0xd6, 0x94, 0x93, 0x56, 0x61, 0xf4, 0xf1, 0xfc, 0x09, 0x30, 0xa5, 0xaf, 0x38, 0x50, 0xcc,
	0xeb, 0x4d, 0xb7, 0x50, 0x5d, 0xbd, 0x43, 0x61, 0xa4, 0xed, 0xf4, 0x01, 0x14, 0x31, 0xc9, 0x42,
	0x47, 0xa8, 0x37, 0x3f, 0xc7, 0x6b, 0xc0, 0xaa, 0xf0, 0x09, 0x9a, 0xc5, 0xbb, 0x21, 0xdf, 0x16,
	0x42, 0x55, 0x5e, 0x5a, 0xa8, 0x16, 0xef, 0x70, 0xc7, 0x70, 0xfe, 0x15, 0x70, 0x5c, 0x69, 0x1e,
	0xf8, 0xe0, 0x5d, 0x0e, 0x20, 0xff, 0xdd, 0x1d, 0xec, 0xa6, 0xcb, 0x38, 0x6f, 0x77, 0x39, 0xaf,
	0xa6, 0xad, 0x98, 0x95, 0x7e, 0x01, 0xc5, 0x49, 0x45, 0xd4, 0xbe, 0x9f, 0x7a, 0xee, 0xec, 0x1f,
	0x22, 0x0f, 0xa0, 0xe2, 0x18, 0x08, 0x6b, 0x23, 0xed, 0x5e, 0x6b, 0xa8, 0x43, 0xcc, 0x83, 0x77,
	0xf8, 0x64, 0x84, 0x7d, 0xfe, 0x90, 0xaf, 0x6f, 0x3c, 0xb1, 0xf9, 0x1f, 0xc2, 0xc6, 0x08, 0xab,
	0x58, 0x4e, 0xdf, 0x19, 0xf7, 0x46, 0xd8, 0x86, 0xbf, 0x42, 0x72, 0x84, 0x60, 0x84, 0xed, 0xfe,
	0x02, 0x00, 0x00, 0xff, 0xff, 0x45, 0x7f, 0xfa, 0xc6, 0x13, 0x01, 0x00, 0x00,
}
